### ISSUE TITLE
If inject_script is not permitted, this tag will not call gtmOnSuccess or gtmOnFailure

### ISSUE THREAD

**Issue by semisight** [bambuser/bambuser-one-to-one-gtm-template#2]
https://github.com/bambuser/bambuser-one-to-one-gtm-template/blob/b70dcb1c4f7aa831954d0d57c346fbcaa87a829a/template.tpl#L214

This `if` statement needs an `else` block that calls (likely) `data.gtmOnFailure()`.

**Comment by Milvan** [comment]
Makes total sense. Will after review merge this PR
https://github.com/bambuser/bambuser-one-to-one-gtm-template/pull/3
that fixes this issue
